### ISSUE TITLE
Newer loader work breaks with steamoverlay (e.g. in ASTRONEER or Shadow of War)

### ISSUE THREAD

**Issue by grazzolini** [felixdoerre/primus_vk#53] opened 2019-09-19 01:19 UTC
I have updated Arch's package to version 1.2 to find out it breaks a very specific game for me, ASTRONEER. I've done a bit of bisecting into which specific commit breaks it and it seems that 134535c4d60cc1d3271d825ade08470540af539b triggers it.

I don't know if it breaks any other games, but I've tested a few others, using steam/proton/dxvk, and the ones I've tested worked fine.

What would you need in terms of debugging to help find out why this newer loader breaks only this game?

**Comment by felixdoerre** [comment] 2019-09-19 04:51
The first question would be: What exactly means "breaks"? Segfault and crash? Segfault during startup? The game refusing to start with an error message? Something else?

If there is a segfault, it would be best to have a stacktrace: So use primus_vk with debug symbols, and then gdb to generate a stack trace. Also stdout of the game could have hints about how far initialization got and what is wrong.

So more concrete steps on "how to debug" the proton game: You can configure Steam to run the game with `PROTON_DUMP_DEBUG_COMMANDS=1` to get a "runner" in "/tmp/proton_$USER/run" to start the game manually (and see stdout/stderr, for documentation see https://github.com/ValveSoftware/Proton#runtime-config-options). To run the game (including proton) with gdb, I usually patch this runner by changing the last line `.../dist/bin//wine" "${@:-${DEF_CMD[@]}}"` to `.../dist/bin//wine" gdb --args "${@:-${DEF_CMD[@]}}"`.

**Comment by grazzolini** [comment] 2019-09-20 01:40
Ok, so here is the log of the game when called through steam. You can get most of my system relevant information from here. By the way, this is running the game with the debug compiled version of primus_vk and the following launch option on steam:

PROTON_DUMP_DEBUG_COMMANDS=1 PROTON_LOG=1 pvkrun %command%

[steam-361420.log](https://github.com/felixdoerre/primus_vk/files/3633798/steam-361420.log)

When I use the unmodified ./run script that's created on /tmp, the game is now loading and my machine is not freezing, which is puzzling. Even when running the modified script as you've suggested, it's working. So, the game is not loading from steam only. But it works when calling it using the run scripts.

**Comment by felixdoerre** [comment] 2019-09-20 06:01
Yes, the proton-debug scripts only cover the "run with steam and proton"-part but leave out any additional configuration. Sorry, that I missed to explain that. I generally find them useful, especially for games that refuse to start if not started from steam. Those run-scripts set all environment variables so that the game believes it is run from Steam, which allows to run/debug the game directly. Why your machine freezes when you run it with gdb, is unclear to me.

So its pretty clear that it crashes in the steamoverlay:
```
0x00007f20050eb7c2 vkCreateSwapchainKHR+0xffffffffffffffff() in steamoverlayvulkanlayer.so (0x0000000000000001)
0x00007f20050eb7c2 vkCreateSwapchainKHR+0xffffffffffffffff in steamoverlayvulkanlayer.so: movq	0x0000000000000018(%rax),%rax
```
Have you tried disabling the steam overlay with `DISABLE_VK_LAYER_VALVE_steam_overlay_1=1` as an additional environment variable?

I also observed something similar in another game, that crashes as well, however it crashes in a different function of steamoverlay.

**Comment by grazzolini** [comment] 2019-09-20 18:21
It works when running with DISABLE_VK_LAYER_VALVE_steam_overlay_1=1. Do you think this might be a bug on the steam overaly for vulkan? I can report this upstream if it is.

**Comment by felixdoerre** [comment] 2019-09-20 18:27
I think it is, but I don't have the source code of the overlay to verify and check what's happening. When you report this issue upstream could you share a reference to the report so I can keep an eye on it? (maybe I can help, if this turns out to be a primus_vk issue after all)

**Comment by grazzolini** [comment] 2019-09-20 19:27
This seems to be affecting also non proton games. Dota 2, Dota Underlords, Kerbal Space Program, all of them don't work with primus_vk 1.2 here. Not even passing the DISABLE_VK_LAYER_VALVE_steam_overlay_1=1

**Comment by felixdoerre** [comment] 2019-09-21 21:51
I believe I found the issue (and it is a primus_vk issue). Could you try 9b8c449 and see if the problem persists?

**Comment by grazzolini** [comment] 2019-09-22 02:16
That one fix ASTRONEER for sure. But the funny thing is, I don't think I've tried using Dota 2 or KSP with vulkan before, but neither works with primus_vk (I'm not sure if it's related). Also, Dota Underlods, which is pure vulkan, doesn't work with primus_vk as well. I have backported that commit and pushed a new package on Arch.

Having said that, I think there's still some work to do on native games.

**Comment by felixdoerre** [comment] 2019-09-22 08:17
I've just tried KSP, and I can't find an option for the game to use Vulkan and the "normal" primusrun-variant for OpenGL seems to work well. I've also just installed Dota 2 with the "Vulkan DLC" and launched it with `-vulkan` and also that has no problems on my system. Dota Underlords also works well with primus_vk here, I am unable to launch it myself from the command line because I don't seem to be able to initialize the "steam runtime" correctly, but launching it from Steam works flawlessly.

So all in all this seems to me more like being a setup issue than an actual bug. (And I think, you can mark the comment for ASTRONEER on Proton regarding the overlay as resolved)

**Comment by grazzolini** [comment] 2019-09-22 13:27
For KSP you have to run it using: pvkrun %command% -force-vulkan, [here](https://wiki.kerbalspaceprogram.com/wiki/Startup_parameters) are the options.

For dota 2, I have the vulkan DLC and I can run using vulkan on my intel igpu, but if I run pvkrun %command% with vulkan, it doesn't work. I can run fine the opengl version with pvkrun (because it fallback to primus)

Same for Underlords (runs fine on the igpu), but doesn't with pvkrun. And since it's pure vulkan, I can't get it running on my nvidia card. If it helps I can attach my system info here.

**Comment by felixdoerre** [comment] 2019-09-22 13:58
Hmm... the vulkan mode of my KSP seems broken, even when I launch without primus_vk.
```
 ./KSP.x86_64 -force-vulkan
Set current directory to /home/user/Steam/SteamLinuxLibrary/steamapps/common/Kerbal Space Program
Found path: /home/user/Steam/SteamLinuxLibrary/steamapps/common/Kerbal Space Program/KSP.x86_64
Mono path[0] = '/home/user/Steam/SteamLinuxLibrary/steamapps/common/Kerbal Space Program/KSP_Data/Managed'
Mono config path = '/home/user/Steam/SteamLinuxLibrary/steamapps/common/Kerbal Space Program/KSP_Data/Mono/etc'
Preloaded 'ScreenSelector.so'
Preloaded 'libkeyboard.so'
Preloaded 'liblingoona.grammar.kerbal.so'
Preloaded 'libsteam_api.so'
Unable to preload the following plugins:
	ScreenSelector.so
	libkeyboard.so
	liblingoona.grammar.kerbal.so
	libsteam_api.so
Player data archive not found at `/home/user/Steam/SteamLinuxLibrary/steamapps/common/Kerbal Space Program/KSP_Data/data.unity3d`, using local filesystem
Logging to /home/user/.config/unity3d/Squad/Kerbal Space Program/Player.log
Xlib:  extension "NV-GLX" missing on display ":0".
```
So I cannot test what primus_vk does wrong here. As for the other games: Do they crash? Do they hang? Can you provide a backtrace if they crash?

**Comment by grazzolini** [comment] 2019-09-22 14:49
They crash:

**Comment by felixdoerre** [comment] 2019-09-22 18:26
The location looks very similar to the stack trace from #51. However I still don't know what is wrong there.

**Comment by grazzolini** [comment] 2019-09-23 00:58
So, today I got some time to dig a little bit more into this issue. I have vulkan-intel and primus_vk installed, as I should to be able to run games using bumblebee + primus. If I run pvkrun vulkaninfo, it detects both cards, my intel as the first one and my nvidia as second. And, it lists the layers. At some point, vulkaninfo segfaults. I've noticed this before and talked with the vulkan-tools maintainer for Arch and he told me that was normal. And, since primus_vk works for the games I was playing at the time, I didn't consider it important.

So, today I tried to run things using nvidia-xrun. From within that Xorg server, I got the same result when running vulkaninfo, it lists both cards, but the nvidia as first and intel as second (because of nvidia-xrun, that's expected), but it segfaults as well. This means, of course, my icd.d directory has the 3 json files, intel's, primus_vk's and nvidia's.

So, I go and remove both vulkan-intel and primus_vk. Tried running vulkaninfo, it only detects my nvidia card and it doesn't segfault. Then, I tried to run dota 2, and, to my surprise, it runs flawlessly. Same with Dota Underlords.

I think there's a bigger issue at play here, other than only primus_vk. And, by the way, it doesn't work if I force the order of the icd's, I need to completely remove both vulkan-intel and primus_vk for it to work under nvidia-xrun.

**Comment by felixdoerre** [comment] 2019-09-23 05:19
> At some point, vulkaninfo segfaults
I think that's not good. I just debugged my `vulkaninfo` (it turned out to segfault as well when run with primus_vk) and found out what causes the segfault. Here is a fix: bfed91d
Now `vulkaninfo` terminates successfully both with and without primus_vk on my system.

Could you try the fix, if it improves running Dota on your system?

**Comment by bno1** [comment] 2019-09-23 08:51
About the vulkaninfo crash, I get the crash when running `ENABLE_PRIMUS_LAYER=1 primusrun vulkaninfo` but not when running `ENABLE_PRIMUS_LAYER=1 optirun -b primus vulkaninfo`.

**Comment by grazzolini** [comment] 2019-09-23 22:04
I have applied that patch and indeed I can run vulkaninfo with pvkrun without any segfault. but dota 2 and dota underlords won't run regardless.

I have switched my configuration to use the nvidia card only, without vulkan-intel + bumblebee + primus + primus_vk, and both games play just fine using the nvidia card. But, that's not optimal, because I'm not getting any of the benefits of running the dgpu only when needed.

**Comment by felixdoerre** [comment] 2019-09-24 05:00
From my point of view `ENABLE_PRIMUS_LAYER=1 optirun -b none`, `ENABLE_PRIMUS_LAYER=1 optirun -b primus` and `ENABLE_PRIMUS_LAYER=1 primusrun` should all work. I usually start applications with `optirun` and it works fine.

@grazzolini Could you please run dota 2 / dota underlords with gdb and validate the contents of the `physicalDevice` parameter to `vkGetPhysicalDeviceProperties`?

**Comment by felixdoerre** [comment] 2019-10-25 17:00
I close this issue, as the original problem (mentioned in the issue's title) is resolved now and the segfault seems to be similar to #51

**Closed by felixdoerre** 2019-10-25 17:00 UTC

**Comment by grazzolini** [comment] 2019-10-25 20:31
Yes, this is ok to close. Also, primus_vk on Arch backports the patches.

**Comment by felixdoerre** [comment] 2019-10-25 21:21
I think that I will release those changes in the next days as v1.3. I hoped to be able to solve the other segfault, but was not able to reproduce it in a clean arch live system. So now I'm still cleaning up other things and will then release this version as v1.3.
