### ISSUE TITLE
Use VK external fd extensions (they are core 1.1 spec)

### ISSUE THREAD

**Issue by boberfly** [felixdoerre/primus_vk#25] opened 2019-02-27 08:21 UTC
Hi all,

I was wondering if it's possible to use these extensions for better syncing between the display's swapchan with the rendering device's images?

https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#VK_KHR_external_memory

https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#VK_KHR_external_fence

https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#VK_KHR_external_semaphore

I'd like to implement this but I am not very adept at the current codebase. After discovering https://github.com/felixdoerre/primus_vk/issues/24 I did notice it was full of hitches.

Cheers

**Comment by felixdoerre** [comment] 2019-03-01 23:17
As already discussed in #2 the external fd extensions can only be used to share memory between two applications accessing the same device. Exporting memory and importing it to another physical device is not possible with that extensions. It can be seen in this table (https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#external-memory-handle-types-compatibility) that the device and driver UUID must match.

As to external fences and semaphores I can not see where additional synchronization is needed in the current source code where those extensions can help.

**Comment by felixdoerre** [comment] 2019-06-13 13:07
I already have #2 open for thought and ideas how to reduce image copy, but at the moment there seems no solution. So I am closing this issue as duplicate of #2.

**Closed by felixdoerre** 2019-06-13 13:07 UTC
